### ISSUE TITLE
How to use this.

### ISSUE THREAD

**Issue by mesqueeb** [ybarbaria/chartjs-plugin-crosshoverline#1]
I want to use this plugin, but the ReadMe doesn't have that many information.

I am new to chartjs and was able to create the graph I need, but now I just need to add the crosshair.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/3253920/45491369-87765980-b7a4-11e8-8149-a06b5d2baab7.png">

**Comment by ybarbaria** [comment]
Hello @mesqueeb 
It was an experience, where do you want to use this plugin? Is it an angular project? 
I can help you if you want, I made a typescript for build crosshover pointer.

**Comment by mesqueeb** [comment]
@ybarbaria Thank you for your reply! I need to use it in a VueJS project.  : )
I'm using the vue wrapper for chartjs. https://vue-chartjs.org/

**Comment by ybarbaria** [comment]
Hello @mesqueeb, let me some days for check VuejsChartjs because I use chartJs with angular 2 and i will come back with an solution.

**Comment by mesqueeb** [comment]
@ybarbaria Thank you very much.
Just last night, after much trial and error over the course of a couple of days, I was able to make something work based on some examples I found on the web here and there.

With the vue wrapper and manually editing some part of the code I have a beautiful working example that looks like:

![image](https://user-images.githubusercontent.com/3253920/45728679-0257ce00-bc04-11e8-921e-407c8db60726.png)

### The Code:

See steps 1 - 7.

```js
// 1. Import Chart.js so you can use the global Chart object
import Chart from 'chart.js'
// 2. Import the `generateChart()` method to create the vue component.
import { generateChart } from 'vue-chartjs'
// 3. Extend on of the default charts
// http://www.chartjs.org/docs/latest/developers/charts.html
Chart.defaults.LineWithLine = Chart.defaults.line
Chart.controllers.LineWithLine = Chart.controllers.line.extend({
  draw: function (ease) {
    Chart.controllers.line.prototype.draw.call(this, ease)
    if (this.chart.tooltip._active && this.chart.tooltip._active.length) {
      const activePoint = this.chart.tooltip._active[0],
        ctx = this.chart.ctx,
        canvas = ctx.canvas,
        x = activePoint.tooltipPosition().x,
        y = activePoint.tooltipPosition().y
      // draw line
      ctx.save()
      ctx.beginPath()
      // this is the actual crosshair
      ctx.moveTo(x, 0)
      ctx.lineTo(x, canvas.scrollHeight)
      ctx.moveTo(0, y)
      ctx.lineTo(canvas.scrollWidth, y)
      // stylize the crosshair
      ctx.lineWidth = 1
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.5)'
      ctx.setLineDash([3, 3])
      ctx.stroke()
      ctx.restore()
    }
  }
})

// 4. Generate the vue-chartjs component
// First argument is the chart-id, second the chart type.
const CustomLine = generateChart('custom-line', 'LineWithLine')

export default {
  // 5. Extend the CustomLine Component just like you do with the default vue-chartjs charts.
  extends: CustomLine,
  mounted () {
    const data = {/* add data */}
    const options = {
      responsive: true,
      maintainAspectRatio: false,
      // 6. Add these options:
      hover: {
        mode: 'nearest',
        intersect: true
      },
      tooltips: {
        mode: 'index',
        intersect: false,
      },
      /* other options */
    }
    // 7. renderChart
    this.renderChart(data, options)
  }
}
```

**Comment by ybarbaria** [comment]
@mesqueeb  Good job mate ! Did u use my solution ?

**Comment by mesqueeb** [comment]
@ybarbaria No I didn't : ( I used the solution I provided in the comment above.
